language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
sudo: false
script:
  - dotnet build -c Release
  - dotnet test ./src/GameOfLife.xUnit.Tests/GameOfLife.xUnit.Tests.csproj -c Release
  - dotnet test ./src/GameOfLife.mstest.Tests/GameOfLife.mstest.Tests.csproj -c Release