version: 1.0.{build}
image:
- Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  COVERALLS_REPO_TOKEN:
    secure: FF5dP0+mIN5AIn9T92SuuUHxJ+eb97nDC7yg4lHTAhH7hnI+CjKzpLboeWm9M0j8
install:
build_script:
  - dotnet build -c Release
test_script:
- ps: >-

    dotnet tool install coveralls.net --version 1.0.0 --tool-path "${pwd}/tools"

    dotnet test src\GameOfLife.xUnit.Tests\GameOfLife.xUnit.Tests.csproj"" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../
- cmd: .\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --useRelativePaths
