version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: T4HU+3zXxONb3hR4a+rJbE0MctjwMjlbHrYVBaU4BRXp9OAWygYlNUnDZZkG7vHk
install:
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.6;%path%
build_script:
  - tsc.exe .\src\code.ts --outDir out
test_script:
- ps: >-
    nuget install Chutzpah -OutputDirectory packages -Version 4.3.4

    dotnet tool install coveralls.net --version 1.0.0-beta0001 --tool-path tools

    $chutzpah = (Resolve-Path ".\packages\Chutzpah.*\tools\chutzpah.console.exe").ToString()

    & $chutzpah "test\test.js" /failOnError /nologo /coverage /coveragejson chutzpah.json

    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --chutzpah -i chutzpah.json --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID