version: 1.0.{build}
image:
- Visual Studio 2017 Preview
- ubuntu
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: T4HU+3zXxONb3hR4a+rJbE0MctjwMjlbHrYVBaU4BRXp9OAWygYlNUnDZZkG7vHk
install:
- sh: printf "Commands with sh Prefix run on Linux image only"
- sh: sudo apt-get update
- sh: sudo apt-get install dotnet-sdk-2.1.300-rc1-008673 -y
- sh: sudo apt-get install dotnet-runtime-2.1.0-rc1 -y
build_script:
  - dotnet build -c Release
test_script:
- ps: >-

    dotnet tool install coveralls.net --version 1.0.0-beta0003 --tool-path tools

    dotnet test src\GameOfLife.xUnit.Tests\GameOfLife.xUnit.Tests.csproj"" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../
- cmd: .\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --useRelativePaths
- sh: ./tools/csmacnz.Coveralls --opencover -i coverage.xml --useRelativePaths
