version: 1.0.{build}
image:
- Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: T4HU+3zXxONb3hR4a+rJbE0MctjwMjlbHrYVBaU4BRXp9OAWygYlNUnDZZkG7vHk
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    nuget install Chutzpah -OutputDirectory packages -Version 4.3.4

    dotnet tool install coveralls.net --add-source https://ci.appveyor.com/nuget/coveralls-net-t37a9a9unhwk --version 1.1.0-unstable0026 --tool-path tools

    dotnet test src\GameOfLife.xUnit.Tests\GameOfLife.xUnit.Tests.csproj"" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../

    $chutzpah = (Resolve-Path ".\packages\Chutzpah.*\tools\chutzpah.console.exe").ToString()

    & $chutzpah "test\test.js" /failOnError /nologo /coverage /coveragejson chutzpah.json

    $coveralls = ".\tools\csmacnz.Coveralls"

    & $coveralls --opencover -i coverage.xml --parallel 

    & $coveralls --chutzpah -i chutzpah.json --parallel

    & $coveralls csmacnz.Coveralls --completeParallelWork