version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: T4HU+3zXxONb3hR4a+rJbE0MctjwMjlbHrYVBaU4BRXp9OAWygYlNUnDZZkG7vHk
install:
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.6;%path%
build_script:
  - tsc.exe .\src\code.ts --outDir out
test_script:
- ps: >-
    nuget install Chutzpah -OutputDirectory packages -Version 4.3.4

    $chutzpah = (Resolve-Path ".\packages\Chutzpah.*\tools\chutzpah.console.exe").ToString()

    & $chutzpah "test\test.js" /failOnError /nologo /coverage /coveragejson chutzpah.json

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $zipDownloadPath="https://github.com/csMACnz/coveralls.net/releases/download/1.0.0/coveralls.net.1.0.0-windows.zip"

    Invoke-WebRequest -UseBasicParsing $zipDownloadPath -OutFile coveralls-windows.zip

    mkdir coveralls-windows

    Expand-Archive .\coveralls-windows.zip coveralls-windows

    $coveralls = ".\coveralls-windows\csmacnz.Coveralls.exe"

    & $coveralls --chutzpah -i chutzpah.json --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
